from enum import Enum


class PairingState(str, Enum):
    UNPAIRED = "UNPAIRED"
    PAIRING = "PAIRING"
    PAIR_APPROVAL_REQUIRED = "PAIR_APPROVAL_REQUIRED"
    PAIRED = "PAIRED"
    CONNECTED = "CONNECTED"
    DISCONNECTED = "DISCONNECTED"
    RECONNECTING = "RECONNECTING"
